### ISSUE TITLE
Manifest for Kubernetes

### ISSUE THREAD

**Issue by krystofurr** [chrisjohnson00/docker-qBittorrentvpn#98]
Would you have an example manifest for Kubernetes?  I'm using K3s

**Comment by chrisjohnson00** [comment]
It has been a while since I've used this, but there is a helm chart you can use.
I created a clone of someone else's work and updated to my needs.  I think I added support for NFS storage in the chart, other than that it is likely the same.
https://github.com/chrisjohnson00/qbittorrentvpn-chart - chart source
Here's the chart repo, with how to add it to helm: https://github.com/chrisjohnson00/helm-charts

Here's an example `values.yaml` that I used to install it:

```
vpn:
  # For VPN_ENABLED environment variable
  enabled: true
  # For VPN_USERNAME environment variable
  username: xxx
  # For VPN_PASSWORD environment variable
  password: xxx
ingress:
  # Set to true to enable ingress record generation
  enabled: true
  hosts:
  - name: qbittorrent.cluster.int
    path: /
    tls: false
persistence:
  # Stores the downloaded torrents
  downloads:
    enabled: true
    useNFS: true
    NFS:
      path: /data/torrents
      server: 192.168.1.131

resources:
  limits:
    cpu: 4
    memory: 16Gi
  requests:
    cpu: 75m
    memory: 1800Mi

image:
  repository: chrisjohnson00/qbittorrent-openvpn
  tag: latest
  pullPolicy: Always

```

And installing it in a preexisting namespace (media) is:
`helm upgrade qbittorrent my-repo/qbittorrent --install --atomic -n media -f values.yaml`
